/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurrentAffairsRouteImport } from './routes/current-affairs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as MockTestsIndexRouteImport } from './routes/mock-tests.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes.$slug'
import { Route as MockTestsSlugRouteImport } from './routes/mock-tests.$slug'
import { Route as DashboardTestsRouteImport } from './routes/dashboard.tests'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CheckoutCourseSlugRouteImport } from './routes/checkout.$courseSlug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTestsRouteImport } from './routes/admin.tests'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCurrentAffairsRouteImport } from './routes/admin.current-affairs'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAffairsRoute = CurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsIndexRoute = MockTestsIndexRouteImport.update({
  id: '/mock-tests/',
  path: '/mock-tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsSlugRoute = MockTestsSlugRouteImport.update({
  id: '/mock-tests/$slug',
  path: '/mock-tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestsRoute = DashboardTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCourseSlugRoute = CheckoutCourseSlugRouteImport.update({
  id: '/checkout/$courseSlug',
  path: '/checkout/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurrentAffairsRoute = AdminCurrentAffairsRouteImport.update({
  id: '/current-affairs',
  path: '/current-affairs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/current-affairs': typeof AdminCurrentAffairsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$courseSlug': typeof CheckoutCourseSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/mock-tests/$slug': typeof MockTestsSlugRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mock-tests/': typeof MockTestsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/current-affairs': typeof AdminCurrentAffairsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$courseSlug': typeof CheckoutCourseSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/mock-tests/$slug': typeof MockTestsSlugRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/mock-tests': typeof MockTestsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/current-affairs': typeof CurrentAffairsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/current-affairs': typeof AdminCurrentAffairsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$courseSlug': typeof CheckoutCourseSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/mock-tests/$slug': typeof MockTestsSlugRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/mock-tests/': typeof MockTestsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/current-affairs'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/current-affairs'
    | '/admin/notifications'
    | '/admin/students'
    | '/admin/tests'
    | '/blog/$slug'
    | '/checkout/$courseSlug'
    | '/courses/$slug'
    | '/dashboard/courses'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/tests'
    | '/mock-tests/$slug'
    | '/quizzes/$slug'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/dashboard/'
    | '/mock-tests/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/current-affairs'
    | '/login'
    | '/signup'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/current-affairs'
    | '/admin/notifications'
    | '/admin/students'
    | '/admin/tests'
    | '/blog/$slug'
    | '/checkout/$courseSlug'
    | '/courses/$slug'
    | '/dashboard/courses'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/tests'
    | '/mock-tests/$slug'
    | '/quizzes/$slug'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/dashboard'
    | '/mock-tests'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/current-affairs'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/admin/blog'
    | '/admin/courses'
    | '/admin/current-affairs'
    | '/admin/notifications'
    | '/admin/students'
    | '/admin/tests'
    | '/blog/$slug'
    | '/checkout/$courseSlug'
    | '/courses/$slug'
    | '/dashboard/courses'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/tests'
    | '/mock-tests/$slug'
    | '/quizzes/$slug'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/dashboard/'
    | '/mock-tests/'
    | '/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  CurrentAffairsRoute: typeof CurrentAffairsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutCourseSlugRoute: typeof CheckoutCourseSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  MockTestsSlugRoute: typeof MockTestsSlugRoute
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  MockTestsIndexRoute: typeof MockTestsIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-affairs': {
      id: '/current-affairs'
      path: '/current-affairs'
      fullPath: '/current-affairs'
      preLoaderRoute: typeof CurrentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/': {
      id: '/mock-tests/'
      path: '/mock-tests'
      fullPath: '/mock-tests/'
      preLoaderRoute: typeof MockTestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/$slug': {
      id: '/mock-tests/$slug'
      path: '/mock-tests/$slug'
      fullPath: '/mock-tests/$slug'
      preLoaderRoute: typeof MockTestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tests': {
      id: '/dashboard/tests'
      path: '/tests'
      fullPath: '/dashboard/tests'
      preLoaderRoute: typeof DashboardTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$courseSlug': {
      id: '/checkout/$courseSlug'
      path: '/checkout/$courseSlug'
      fullPath: '/checkout/$courseSlug'
      preLoaderRoute: typeof CheckoutCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/current-affairs': {
      id: '/admin/current-affairs'
      path: '/current-affairs'
      fullPath: '/admin/current-affairs'
      preLoaderRoute: typeof AdminCurrentAffairsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminCurrentAffairsRoute: typeof AdminCurrentAffairsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestsRoute: typeof AdminTestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminCurrentAffairsRoute: AdminCurrentAffairsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestsRoute: AdminTestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTestsRoute: typeof DashboardTestsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTestsRoute: DashboardTestsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  CurrentAffairsRoute: CurrentAffairsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutCourseSlugRoute: CheckoutCourseSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  MockTestsSlugRoute: MockTestsSlugRoute,
  QuizzesSlugRoute: QuizzesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  MockTestsIndexRoute: MockTestsIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
